# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2.3.2
      - uses: actions/setup-node@v1
        with:
          node-version: "18.14.0"
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: single-outrider-389415/cicd
          tags: latest
          registry: gcr.io
          dockerfile: Dockerfile
          username: _json_key
          password: ${{ secrets.GCP_SERVICE_ACCOUNT_PK_JSON }}
      - name: Deploy service to Cloud Run
        uses: stefda/action-cloud-run@v1.0
        with:
          image: gcr.io/single-outrider-389415/cicd
          service: cicd
          project: single-outrider-389415
          region: europe-north1
          service key: ${{ secrets.GCP_SERVICE_ACCOUNT_PK_JSON_BASE64 }}
